# Generated by Django 5.0.3 on 2024-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_going_school',
            field=models.BooleanField(default=True),
        ),
    ]
