# Generated by Django 5.0.3 on 2024-06-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_is_going_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college_name',
        ),
    ]
